web/router.ex
defmodule G1.Router do
  use G1.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", G1 do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/registrations", RegistrationController, only: [:new, :create]

    get     "/login",   SessionController, :new
    post    "/login",   SessionController, :create
    delete  "/logout",  SessionController, :delete
  end


  # Other scopes may use custom stacks.
  # scope "/api", G1 do
  #   pipe_through :api
  # end
end

lib/g1/endpoint.ex
defmodule G1.Endpoint do
  use Phoenix.Endpoint, otp_app: :g1

  socket "/socket", G1.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :g1, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_g1_key",
    signing_salt: "frfZIfvl"

  plug G1.Router
end

lib/g1/repo.ex
defmodule G1.Repo do
  use Ecto.Repo, otp_app: :g1
end

web/models/registration.ex
defmodule G1.Registration do
  import Ecto.Changeset, only: [put_change: 3]

  def create(changeset, repo) do
    changeset
    |> put_change(:crypted_password, hashed_password(changeset.params["password"]))
    |> repo.insert()
  end

  def hashed_password(password) do
    Comeonin.Bcrypt.hashpwsalt(password)
  end
end

web/models/session.ex
defmodule G1.Session do
  alias G1.User, as: User

  def login(%{"email" => email, "password" => password}) \
  when not is_nil(email) and not is_nil(password) do
    user = G1.Repo.get_by(User, email: String.downcase(email))
    case authenticate(user, password) do
      true  -> {:ok, user}
      false -> false
    end
  end

  def login(_), do: false

  def current_user(conn) do
    id = Plug.Conn.get_session(conn, :current_user)
    if id, do: G1.Repo.get(User, id)
  end

  def logged_in?(conn), do: !!current_user(conn)

  defp authenticate(user, password) when not is_nil(user) do
    Comeonin.Bcrypt.checkpw(password, user.crypted_password)
  end

  defp authenticate(_, _), do: false
end

web/models/user.ex
defmodule G1.User do
  use G1.Web, :model

  schema "users" do
    field :email, :string
    field :crypted_password, :string
    field :password, :string, virtual: true

    timestamps()
  end
  @required_fields ~w(email password)
  @optional_fields ~w()

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ :empty) do
    struct
    |> cast(params, @required_fields, @optional_fields)
    |> unique_constraint(:email)
    |> validate_format(:email, ~r/@/)
    |> validate_length(:password, min: 5)
  end
end

web/controllers/page_controller.ex
defmodule G1.PageController do
  use G1.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end

  def haml(conn, _params) do
    render conn, "haml.html"
  end
end

web/controllers/registration_controller.ex
defmodule G1.RegistrationController do
  use G1.Web, :controller
  alias G1.User

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render conn, changeset: changeset
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.changeset(%User{}, user_params)

    case G1.Registration.create(changeset, G1.Repo) do
      {:ok, changeset} ->
        conn
        |> put_session(:current_user, changeset.id)
        |> put_flash(:info, "Your account was created")
        |> redirect(to: "/")
      {:error, changeset} ->
        conn
        |> put_flash(:info, "Unable to create account")
        |> render("new.html", changeset: changeset)
    end
  end
end

web/controllers/session_controller.ex
defmodule G1.SessionController do
  use G1.Web, :controller

  def new(conn, _params) do
    render conn, "new.html"
  end

  def create(conn, %{"session" => session_params}) do
    case G1.Session.login(session_params) do
      {:ok, user} ->
        conn
        |> put_session(:current_user, user.id)
        |> put_flash(:success, "Logged In")
        |> redirect(to: "/")
      false ->
        conn
        |> put_flash(:alert, "Invalid Email or Password")
        |> render("new.html")
    end
  end

  def delete(conn, _) do
    conn
    |> delete_session(:current_user)
    |> put_flash(:info, "Logged out")
    |> redirect(to: "/")
  end
end

web/views/error_view.ex
defmodule G1.ErrorView do
  use G1.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule G1.LayoutView do
  use G1.Web, :view

end

web/views/page_view.ex
defmodule G1.PageView do
  use G1.Web, :view

  def hello do
    "hello world"
  end

end

web/views/registration_view.ex
defmodule G1.RegistrationView do
  use G1.Web, :view
end

web/views/session_view.ex
defmodule G1.SessionView do
  use G1.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello G1!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
  <header class="header">
    <nav class="navbar navbar-default">
      <div class="container">
        <ul class="nav navbar-nav navbar-right">
          <%= if logged_in?(@conn) do %>
            <li><p class="navbar-text">Logged in as <%= current_user(@conn).email %></p></li>
            <li>
            <%= link "Logout", to: session_path(@conn, :delete), method: :delete, class: "navbar-text" %>
            </li>
          <% else %>
            <li><%= link "Login", to: "/login" %></li>
            <li><%= link "Register", to: registration_path(@conn, :new) %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </header>

  <div class="container">
    <p class="alert alert-success" role="alert"><%= get_flash(@conn, :success) %></p>
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-warning" role="alert"><%= get_flash(@conn, :alert) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  </div>

  <main role="main">
  <div class="container">
    <%= render @view_module, @view_template, assigns %>
  </div>
  </main>

</div> <!-- /container -->
<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
</body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="https://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>